### ISSUE TITLE
Pymem Issues

### ISSUE THREAD

**Issue by aidensala** [Snaacky/Ruby#6]
# Issues With The PyMem Module

I'm running on py2.7.14, and when I first ran I got` no module named enum`, so of course I installed the module with pip (should add enum to requirements). Now I'm getting `'module' object has no attribute 'PULONG'`. I'm not sure if these are just errors in pymem, or it has something to do with the fact that I'm running < Python3

**Comment by Snaacky** [comment]
The memory editing library that this project relies on has a minimum requirement of Python 3.5 as stated in the [README](https://github.com/Snaacky/Ruby/blob/master/README.md).

[Also, you may want to look into updating your Python or at the very least running two separate versions of Python because Python 2.7's EOL is only a year away now.](https://pythonclock.org/)
